+ Incorporated all of autopkg-trust-tool features into this tool.

diff --git a/recipe-tool b/recipe-tool
--- a/recipe-tool
+++ b/recipe-tool
@@ -42,6 +42,8 @@ RECIPE_NAMES=()
 ADD_CATALOGS=()
 REMOVE_CATALOGS=()
 FORMAT_SUBDIR=0
+TRUST=0
+VERIFY=0
 #### ####
 
 #### Non-Customizable Functions ####
@@ -573,6 +575,59 @@ debug_state_custom()
 	debug_print -e -B -S "(${FUNCNAME[0]}) Started ${FUNCNAME[0]} function with args: $*"
 	debug_print -e -B -S "(${FUNCNAME[0]}) Current Custom Variable State: "
 }
+get_autopkg_trust_behavior()
+{
+	debug_print -e -B -S "(${FUNCNAME[0]}) Started ${FUNCNAME[0]} function with args: $*"
+	R=$(defaults read com.github.autopkg FAIL_RECIPES_WITHOUT_TRUST_INFO 2>/dev/null)
+	if [ $? -ne 0 ]; then
+		debug_print -B -S "(${FUNCNAME[0]}) Key FAIL_RECIPES_WITHOUT_TRUST_INFO not set or some other error ($?)."
+		return 66
+	else
+		case "$R" in
+			0)
+				debug_print -R -S "(${FUNCNAME[0]}) FAIL_RECIPES_WITHOUT_TRUST_INFO set to False."
+				return 0
+				;;
+			1)
+				debug_print -G -S "(${FUNCNAME[0]}) FAIL_RECIPES_WITHOUT_TRUST_INFO set to True."
+				return 1
+				;;
+			*)
+				debug_print -R -S "(${FUNCNAME[0]}) FAIL_RECIPES_WITHOUT_TRUST_INFO set to Unknown value: $R."
+				return 66
+				;;
+		esac
+	fi
+}
+set_autopkg_trust_behavior()
+{
+	debug_print -e -B -S "(${FUNCNAME[0]}) Started ${FUNCNAME[0]} function with args: $*"
+	[ $# -lt 1 ] && fail_notice_exit "(${FUNCNAME[0]}) Not enough arguments provided."
+	case "$1" in
+		0 | "true" | "yes" | "YES" | "TRUE")
+			action="write"
+			value="-bool YES"
+			;;
+		1 | "false" | "no" | "NO" | "FALSE")
+			action="write"
+			value="-bool NO"
+			;;
+		"NONE" | "none" | "RESET" | "reset")
+			value=""
+			action="delete"
+			;;
+		*)
+			fail_notice_exit "(${FUNCNAME[0]}) Incorrect argument provided."
+			;;
+	esac
+	defaults $action com.github.autopkg FAIL_RECIPES_WITHOUT_TRUST_INFO $value
+	return_code=$?
+	case "$return_code" in
+		0) debug_print -G -S "(${FUNCNAME[0]}) Successful action $action to FAIL_RECIPES_WITHOUT_TRUST_INFO with value: $value" ;;
+		*) debug_print -R -S "(${FUNCNAME[0]}) Failed action $action to FAIL_RECIPES_WITHOUT_TRUST_INFO with value: $value" ;;
+	esac
+	return $return_codes
+}
 main_custom()
 {
 	debug_print -e -B -S "(${FUNCNAME[0]}) Started ${FUNCNAME[0]} function with args: $*"
@@ -593,6 +648,18 @@ main_custom()
 		if [ $INFO -eq 1 ]; then
 			local_print -C -S "$BLOCK Info for $R $BLOCK"
 			autopkg info --override-dir="$OVERRIDE_DIR" "$R"
+			local_print -C -S "$BLOCK $BLOCK"
+		fi
+		if [ $TRUST -eq 1 ]; then
+			local_print -C -S "$BLOCK Trust Action for $R $BLOCK"
+			autopkg update-trust-info --override-dir="$OVERRIDE_DIR" "$R"
+			[ $? -eq 0 ] && local_print -G -S "Trust Successful for $R"
+			[ $? -ne 0 ] && local_print -R -S "Trust Failed for $R"
+			local_print -C -S "$BLOCK $BLOCK"
+		fi
+		if [ $VERIFY -eq 1 ]; then
+			local_print -C -S "$BLOCK Verify Action $R $BLOCK"
+			autopkg verify-trust-info --override-dir="$OVERRIDE_DIR" "$R"
 			local_print -C -S "$BLOCK $BLOCK"
 		fi
 	done
@@ -623,6 +690,13 @@ parse_args_custom()
 				;;
 			"--format-repo-subdir") FORMAT_SUBDIR=$(var_toggle $FORMAT_SUBDIR) ;;
 			"--select" | "--s") SELECT=$(var_toggle $SELECT) ;;
+			"--set-trust-behavior-"*)
+				set_autopkg_trust_behavior "$(echo $1 | cut -d '-' -f6)"
+				[ $? -ne 0 ] && fail_notice_exit "Failed to set FAIL_RECIPES_WITHOUT_TRUST_INFO to $(echo $1 | cut -d '-' -f6)"
+				exit 0
+				;;
+			"--trust" | "-t") TRUST=$(var_toggle $TRUST) ;;
+			"--verify" | "-v") VERIFY=$(var_toggle $VERIFY) ;;
 			*)
 				debug_print -e -B -S "Processing Unknown Argument: $1"
 				if [ ${#} -eq 1 ];then
@@ -714,6 +788,16 @@ usage_custom()
 	echo -n "	--format-repo-subdir: Format the MUNKI_REPO_SUBDIR to be developer_name/app_name. Default: "
 	[ $FORMAT_SUBDIR -eq 0 ] && local_print -R "$(var_state $FORMAT_SUBDIR)"
 	[ $FORMAT_SUBDIR -eq 1 ] && local_print -G "$(var_state $FORMAT_SUBDIR)"
+	echo -n "	[--trust|-t]: Trust a recipe. Default: "
+	[ $TRUST -eq 0 ] && local_print -R "$(var_state $TRUST)"
+	[ $TRUST -eq 1 ] && local_print -G "$(var_state $TRUST)"
+	echo -n "	[--verify|-v]: Verify trust info. Default: "
+	[ $VERIFY -eq 0 ] && local_print -R "$(var_state $VERIFY)"
+	[ $VERIFY -eq 1 ] && local_print -G "$(var_state $VERIFY)"
+	echo ""
+	echo "	[OPTIONS]"
+	echo "	--get-trust-behavior: Retrieve the value of FAIL_RECIPES_WITHOUT_TRUST_INFO from com.github.autopkg."
+	echo "	--set-trust-behavior-[true|false|none]: Set the value of FAIL_RECIPES_WITHOUT_TRUST_INFO for com.github.autopkg to true, false or none."
 }
 #### ####
 
